# -*- coding: utf-8 -*-
"""ChatBot_pyCode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11zOQ4rd-uRru8ERehydmiO-u5kvDq0HP
"""

!pip install aiml python-aiml

import aiml 
kernel=aiml.Kernel()
kernel.learn("PizzaBoT Ron.xml")
while True:
  print(kernel.respond(input("Enter your message : ")))

